import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

const sidebars: SidebarsConfig = {
  docsSidebar: [
    {
      type: "category",
      label: "Getting Started",
      link: { type: "generated-index" },
      items: [{ type: "autogenerated", dirName: "getting-started" }],
    },
    {
      type: "category",
      label: "Connections",
      link: { type: "doc", id: "connections/index" },
      items: [{ type: "autogenerated", dirName: "connections" }],
    },
    {
      type: "category",
      label: "Architecture",
      link: { type: "generated-index" },
      items: [{ type: "autogenerated", dirName: "architecture" }],
    },
    {
      type: "category",
      label: "API Reference",
      link: { type: "generated-index" },
      items: [{ type: "autogenerated", dirName: "api-reference" }],
    },
    {
      type: "category",
      label: "SDK Guide",
      link: { type: "generated-index" },
      items: [{ type: "autogenerated", dirName: "sdk" }],
    },
    {
      type: "category",
      label: "OpenClaw Integration",
      link: { type: "doc", id: "openclaw/index" },
      className: "sidebar-openclaw-highlight",
      collapsible: true,
      collapsed: false,
      items: [{ type: "autogenerated", dirName: "openclaw" }],
    },
    {
      type: "category",
      label: "Security",
      link: { type: "generated-index" },
      items: [{ type: "autogenerated", dirName: "security" }],
    },
    {
      type: "category",
      label: "Development Guide",
      link: { type: "generated-index" },
      items: [{ type: "autogenerated", dirName: "development" }],
    },
  ],
};

export default sidebars;
